language: minimal

branches:
  only:
    - main  # or the branch you want to deploy from

install:
  - echo "No dependencies to install"

script:
  - echo "No build step needed"

before_deploy:
  - sudo apt-get update
  - sudo apt-get install lftp

deploy:
  provider: script
  script: lftp -e "set ftp:ssl-allow no; mirror -R ./ sitemirror; quit" -u $if0_37117609,$Skikda1970  ftp://$ftpupload.net
  skip_cleanup: true
  on:
    branch: main
